vim.pack.add({
	{ src = "https://github.com/nvim-mini/mini.nvim" },
	{ src = "https://github.com/nvim-lua/plenary.nvim" },
	{ src = "https://github.com/MunifTanjim/nui.nvim" },
	{ src = "https://github.com/nvim-tree/nvim-web-devicons" },
	{ src = "https://github.com/nvim-neo-tree/neo-tree.nvim" },
	{ src = "https://github.com/folke/which-key.nvim" },
	{ src = "https://github.com/ibhagwan/fzf-lua" },
	{ src = "https://github.com/rachartier/tiny-code-action.nvim" },
	{ src = "https://github.com/smjonas/inc-rename.nvim" },
	{ src = "https://github.com/TheNoeTrevino/haunt.nvim" },
	{ src = "https://github.com/lewis6991/gitsigns.nvim" },
	{ src = "https://github.com/rebelot/kanagawa.nvim" },
	{ src = "https://github.com/sainnhe/gruvbox-material" },
	{ src = "https://github.com/ember-theme/nvim", name = "ember" },
	{ src = "https://github.com/webhooked/kanso.nvim" },
	{ src = "https://github.com/romus204/tree-sitter-manager.nvim" },
	{ src = "https://github.com/saghen/blink.cmp", version = vim.version.range("1.*") },
	{ src = "https://github.com/stevearc/conform.nvim" },
	{ src = "https://github.com/mfussenegger/nvim-lint" },
	{ src = "https://github.com/mason-org/mason.nvim" },
	{ src = "https://github.com/mason-org/mason-lspconfig.nvim" },
	{ src = "https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim" },
	{ src = "https://github.com/mfussenegger/nvim-dap" },
	{ src = "https://github.com/jay-babu/mason-nvim-dap.nvim" },
	{ src = "https://github.com/mfussenegger/nvim-dap-python" },
	{ src = "https://github.com/leoluz/nvim-dap-go" },
	{ src = "https://github.com/igorlfs/nvim-dap-view" },
	{ src = "https://github.com/neovim/nvim-lspconfig" },
	{ src = "https://github.com/mfussenegger/nvim-jdtls" },
	{ src = "https://github.com/rachartier/tiny-cmdline.nvim" },
	{ src = "https://github.com/windwp/nvim-ts-autotag" },
})

local plugin_modules = {
	"plugins.mini",
	"plugins.which_key",
	"plugins.neo_tree",
	"plugins.fzf",
	"plugins.tiny_code_action",
	"plugins.inc_rename",
	"plugins.haunt",
	"plugins.gitsigns",
	"plugins.treesitter",
	"plugins.blink",
	"plugins.conform",
	"plugins.lint",
	"plugins.mason",
	"plugins.dap",
	"plugins.jdtls",
	"plugins.lsp",
	"plugins.tiny_cmdline",
	"plugins.autotag",
}

for _, module in ipairs(plugin_modules) do
	require(module)
end
