[settings]
lockfile = true

[tools]
fzf = "latest"
zoxide = "latest"
eza = "latest"
ripgrep = "latest"
neovim = "latest"
zellij = "latest"
lazygit = "latest"
gh = "latest"
glab = "latest"
duf = "latest"
git-cliff = "latest"
pre-commit = "latest"
k9s = "latest"
bat = "latest"
"github:calamity-m/peanutbutter" = "latest"
"github:calamity-m/fml" = "latest"
dive = "latest"
helm = "latest"
kubectl = "latest"
k0sctl = "latest"
minikube = "latest"
"cargo:mermaid-rs-renderer" = "latest"
mark = "latest"
jwtui = { version = "latest", exe = "jwtui" }
jwt = "latest"
vhs = "latest"
ttyd = "latest"
gradle = "latest"
