[tools]
fzf = "latest"
zoxide = "latest"
eza = "latest"
ripgrep = "latest"
neovim = "latest"
zellij = "latest"
lazygit = "latest"
gh = "latest"
glab = "latest"
duf = "latest"
git-cliff = "latest"
pre-commit = "latest"
k9s = "latest"
bat = "latest"
"github:calamity-m/peanutbutter" = "latest"
